apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  template:
    metadata:
      name: api-gateway-app
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: quocbao64/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-gateway-app
