apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  template:
    metadata:
      name: order-service-app
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: quocbao64/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
      restartPolicy: Always
  selector:
    matchLabels:
      app: order-service-app
