apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-app
  labels:
    app: email-service-app
spec:
  replicas: 1
  template:
    metadata:
      name: email-service-app
      labels:
        app: email-service-app
    spec:
      containers:
        - name: email-service-app
          image: quocbao64/email-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
      restartPolicy: Always
  selector:
    matchLabels:
      app: email-service-app
