apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  selector:
    app: eureka
  ports:
    - port: 80
      targetPort: 8761
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka